// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../../lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`

class AppConfig {
  final double blendFactor;
  final List<Lab> colors;
  final double ditherAmount;
  final int spatialAveragingRadius;

  const AppConfig({
    required this.blendFactor,
    required this.colors,
    required this.ditherAmount,
    required this.spatialAveragingRadius,
  });

  @override
  int get hashCode =>
      blendFactor.hashCode ^
      colors.hashCode ^
      ditherAmount.hashCode ^
      spatialAveragingRadius.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppConfig &&
          runtimeType == other.runtimeType &&
          blendFactor == other.blendFactor &&
          colors == other.colors &&
          ditherAmount == other.ditherAmount &&
          spatialAveragingRadius == other.spatialAveragingRadius;
}
