// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../../lib.dart';
import 'colorize.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<SrgbF32> hexToRgb({required String input}) =>
    RustLib.instance.api.crateApiColorizerUtilsHexToRgb(input: input);

Future<Lab> interpolateColor({
  required Lab color1,
  required Lab color2,
  required double t,
}) => RustLib.instance.api.crateApiColorizerUtilsInterpolateColor(
  color1: color1,
  color2: color2,
  t: t,
);

Future<List<List<(double, double, double)>>> computeIntegralImage({
  required RgbImage image,
}) => RustLib.instance.api.crateApiColorizerUtilsComputeIntegralImage(
  image: image,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Srgb < f32 >>>
abstract class SrgbF32 implements RustOpaqueInterface {}
